version: '3'

services:

  memcached:
    build:
      context: .
      dockerfile: memcached.Dockerfile
    volumes:
      - memcached_socket:/home/memcached_socket:rw

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=gazelle
      - MYSQL_USER=gazelle
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql_cnf:/etc/mysql/conf.d:ro
      - ./mysql_data:/var/lib/mysql:rw

  db_initializer:
    build:
      context: ..
      dockerfile: docker/db_initializer.Dockerfile
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_initializer_pipe:/db_initializer_pipe:rw

  sphinxsearch:
    build:
      context: ..
      dockerfile: docker/sphinxsearch.Dockerfile
    depends_on:
      - db_initializer
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_initializer_pipe:/db_initializer_pipe:ro
      - ./wait_db_ready.sh:/home/wait_db_ready.sh:ro

  ocelot:
    build:
      context: ../Ocelot
      dockerfile: docker/ocelot.Dockerfile
    depends_on:
      - db_initializer
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=gazelle
      - MYSQL_USER=gazelle
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - GAZELLE_HOST=gazelle
      - GAZELLE_SITE_PASSWORD=${GAZELLE_SITE_PASSWORD}
      - GAZELLE_REPORT_PASSWORD=${GAZELLE_REPORT_PASSWORD}
      - OCELOT_LISTEN_PORT=2710
    volumes:
      - db_initializer_pipe:/db_initializer_pipe:ro
      - ./wait_db_ready.sh:/home/wait_db_ready.sh:ro

  gazelle_log_collector:
    build:
      context: .
      dockerfile: gazelle_log_collector.Dockerfile
    volumes:
      - gazelle_log_pipe:/gazelle_log_pipe:ro

  php_fpm:
    build:
      context: .
      dockerfile: php_fpm.Dockerfile
    depends_on:
      - gazelle_log_collector
    volumes:
      - ../www:/var/www/html:ro
      - gazelle-config-php:/gazelle-config-php:ro
      - memcached_socket:/home/memcached_socket:rw
      - gazelle_log_pipe:/gazelle_log_pipe:rw

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx.Dockerfile
    depends_on:
      - php_fpm
      - ocelot
      - memcached
      - sphinxsearch
    ports:
      - '8080:80'
    environment:
      - GAZELLE_ENCKEY=${GAZELLE_ENCKEY}
      - GAZELLE_REPORT_PASSWORD=${GAZELLE_REPORT_PASSWORD}
      - GAZELLE_RSS_KEY=${GAZELLE_RSS_KEY}
      - GAZELLE_SCHEDULE_KEY=${GAZELLE_SCHEDULE_KEY}
      - GAZELLE_SITE_PASSWORD=${GAZELLE_SITE_PASSWORD}
      - GAZELLE_SITE_SALT=${GAZELLE_SITE_SALT}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ../nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../www:/var/www/html:ro
      - gazelle-config-php:/gazelle-config-php:rw

volumes:
  db_initializer_pipe:
  gazelle-config-php:
  gazelle_log_pipe:
  memcached_socket:
