version: '3'

services:

  memcached:
    build:
      context: .
      dockerfile: memcached.Dockerfile
    volumes:
      - ./memcached_socket:/home/memcached_socket:rw

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=CXO1oy3Nj2c0PCQrtCUzdiROplIT1NqF
      - MYSQL_DATABASE=gazelle
      - MYSQL_USER=gazelle
      - MYSQL_PASSWORD=YzgJugVqPLOFAAQQjIatiM4BAadloZuj
    volumes:
      - ./mysql_cnf:/etc/mysql/conf.d:ro
      - ./mysql_data:/var/lib/mysql:rw

  db_initializer:
    build:
      context: ..
      dockerfile: docker/db_initializer.Dockerfile
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=CXO1oy3Nj2c0PCQrtCUzdiROplIT1NqF
    volumes:
      - ./db_initializer_pipe:/db_initializer_pipe

  sphinxsearch:
    build:
      context: ..
      dockerfile: docker/sphinxsearch.Dockerfile
    depends_on:
      - db_initializer
    environment:
      - MYSQL_PASSWORD=YzgJugVqPLOFAAQQjIatiM4BAadloZuj
    volumes:
      - ./db_initializer_pipe:/db_initializer_pipe

  ocelot:
    build:
      context: ../../Ocelot
      dockerfile: docker/ocelot.Dockerfile
    depends_on:
      - db_initializer
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=gazelle
      - MYSQL_USER=gazelle
      - MYSQL_PASSWORD=YzgJugVqPLOFAAQQjIatiM4BAadloZuj
      - GAZELLE_HOST=gazelle
      - GAZELLE_SITE_PASSWORD=hTwbqH8vKpKm4i6bTVbc4DcqCmgkaRGL
      - GAZELLE_REPORT_PASSWORD=In7fMmbKCpGuOdrJ8jpZ9A2NAoC8B5Qc
      - OCELOT_LISTEN_PORT=2710
    volumes:
      - ./db_initializer_pipe:/db_initializer_pipe

  php_fpm:
    build:
      context: .
      dockerfile: php_fpm.Dockerfile
    volumes:
      - ../www:/var/www/html:ro
      - ./memcached_socket:/home/memcached_socket:rw

  gazelle_nginx:
    build:
      context: ..
      dockerfile: docker/gazelle_nginx.Dockerfile
    depends_on:
      - php_fpm
      - ocelot
      - memcached
      - sphinxsearch
    ports:
      - '8080:80'
    environment:
      - GAZELLE_ENCKEY=fHxsx3kEB6SgudaMJEnfto1NPEWfkJtQ
      - GAZELLE_REPORT_PASSWORD=In7fMmbKCpGuOdrJ8jpZ9A2NAoC8B5Qc
      - GAZELLE_RSS_KEY=UiybX96X2WdglyXzD77gQn8JuzeEMWGA
      - GAZELLE_SCHEDULE_KEY=xq2yZ3OpAA0GKet1BLLSXwbJg9plfG8Y
      - GAZELLE_SITE_PASSWORD=hTwbqH8vKpKm4i6bTVbc4DcqCmgkaRGL
      - GAZELLE_SITE_SALT=6OrccjMqkKfakTAMoGhAzKxyrisSTg4D
      - MYSQL_PASSWORD=YzgJugVqPLOFAAQQjIatiM4BAadloZuj
    volumes:
      - ../nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../www:/var/www/html
